### ISSUE TITLE
Request to make the get requests faster

### ISSUE THREAD

**Issue by UltimateBoi** [comblock/gopixel#9]
Yo, can you make it get the skyblock ah faster. Right now it takes like 10 seconds. Maybe can you implement a http request socket lib to get it faster and implement that with goroutines. Just a suggestion.

**Comment by comblock** [comment]
I could use something like fasthttp but it will always be slow due to it sending out many many requests, if we're going for speed I could also use easyjson to make the unmarshalling faster. I guess this is a tradeoff between speed and the amount of dependencies. I'll make a PR implementing these changes when I have time,

**Comment by UltimateBoi** [comment]
fasthttp is not necessarily faster but try making your own http request socket library specifically for hypixel. People have said this is much faster.

**Comment by comblock** [comment]
I'll look into it but it sounds like a lot of work so it might take a while.

**Comment by UltimateBoi** [comment]
It dosent have to be too complex just simple tbh

**Comment by comblock** [comment]
Also, I don't think if I write my own implementation of http GET it would actually be faster

**Comment by UltimateBoi** [comment]
eh idk it could be as long as you optimise for hypixels dumb api system

**Comment by comblock** [comment]
I think a better solution would be to actually implement caching, which I am not currently planning on doing. What I will do however is use goroutines to make the `SkyblockActiveAuctions()` method faster

**Comment by UltimateBoi** [comment]
yes ty
